package coding;

public class TV220904D {
/*
    SELECT U.ID
    , (SELECT COUNT(*) FROM PURCHASES P WHERE P.USER_ID = U.ID) AS PURCHASE_COUNT
    , IFNULL((SELECT SUM(C.PRICE)
    FROM PURCHASES P JOIN CHARACTERS C ON C.NAME = P.ITEM
    WHERE P.USER_ID = U.ID
    ), 0) AS TOTAL_PRICE
    FROM GAME_USERS U
    */
}
